### ISSUE TITLE
Create a model + class for every part of the website

### ISSUE THREAD

**Issue by Marwerk** [coyotiv-sose/graduation-project-marwerk#1]
booking
hotel
review
room
user
photos

**Comment by Dr4gon** [comment]
@Marwerk I think it's great you're playing around with the ticket system. Have u already watched my video on your UX designs?

https://coyotiv-school.slack.com/archives/C05HC7A7EAU/p1689351090245659 -> Video review

**Comment by Marwerk** [comment]
@Dr4gon thanks! I'm trying to get in the flow of doing things "properly" in the sense of emulating a real working environment. Gotta keep myself sharp for when I land my first software dev job 😎 

Will watch it shortly, wrapping up a coding sesh 👍🏼 

Appreciate it!

**Comment by Marwerk** [comment]
@Dr4gon thanks for the feedback on the wireframes 👍🏼 great wisdom on UI design and how to draw our attention towards a call to action.

I think after I make the Lean UX canvas, my whole picture of the website will be clearer. I'll incorporate your feedback and Alessandro's at that point 🙏🏼

**Comment by Marwerk** [comment]
Base models created with at least one instance of each
