### ISSUE TITLE
#CleanCode Frontend views

### ISSUE THREAD

**Issue by Dr4gon** [coyotiv-sose/graduation-project-marwerk#42]
@Marwerk First something, you could improve.

A small improvement is the readability on this error in the SignUpView.vue

```
 p.error(v-if='registrationError') {{ registrationError }}
```
My suggestions is

```
 p.error(v-if='registrationFails') {{ registrationFails }}
```
because error already tells the reader, it's an error. It's more fluent and less redundant to write it like a sentence.

**Then the things I like:**

- You write a clean code style. Meaning well structured and understandable code.
- You document well and in the right amount, i.e when it's necessary to do so

**Comment by Marwerk** [comment]
Thanks for the feedback De Long!
